### PR TITLE
Changed timestamp to ISO8601 format with milliseconds.

### PR DESCRIPTION
**Pull request by BrandonLWhite**
Hello, I came across your library and it was exactly the solution I envisioned, using Fody.  I am needing a timestamp that will function for multiple builds per day, so I added ISO8601 format with milliseconds in this pull request.

Please consider this PR.  I realize that it does break or potentially break existing usage that may be expecting just a yyyy-MM-dd format.  I'm willing to make changes at your suggestion.

In the meantime, I have uploaded a build of this to Nuget at https://www.nuget.org/packages/BuildTimestamp/0.3.2 if it may be useful to anyone else.

### CODE REVIEW

**Comment by SimonCropp** [comment]
LGTM. i will bump the major version since it breaking

**Comment by SimonCropp** [comment]
this is now deployed

**Comment by BrandonLWhite** [comment]
Awesome, thank you!  I will unlist the above referenced temporary NuGet package.

**Comment by SimonCropp** [comment]
BTW i also added support for dotnet build

**Pull request merged**
